name: Artifact with Global Retention Days

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RETENTION_DAYS: 10   
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Simulate Build Output with Date
      run: |
        mkdir -p build
        today=$(date '+%d %B %Y')
        expiry=$(date -d "+$RETENTION_DAYS days" '+%d %B %Y')
        echo "Build completed on $today and will be stored until $expiry." > build/build.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/
        retention-days: ${{ env.RETENTION_DAYS }}
